@echo off
echo Starting Image Normalization Tool...
echo Checking for required packages...
pip install -r requirements.txt
echo Starting Application...
python image_normalization_demo.py
pause
